-d C:\git programing projects\SysVerilog\SePeMex\impl\gwsynthesis\SePeMex.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\git programing projects\SysVerilog\SePeMex\src\SePeMex.cst
-cfg C:\git programing projects\SysVerilog\SePeMex\impl\pnr\device.cfg
-gao_crc 1001101001010101
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-rtl_gao
